### ISSUE TITLE
Docker Image: pasa binary is not in $PATH 

### ISSUE THREAD

**Issue by groverj3** [PASApipeline/PASApipeline#117]
Hey there,

After updating some things on our lab's server I now get some annoying perl version mismatch errors related to the sql perl modules. However, I figured I could just run the Docker image instead.

But, I got a bunch of the following error:

```
terminated abnormally: Error, pasa binary [] isn't executable or couldn't be found. at /usr/local/src/PASApipeline/PerlLib/CDNA/PASA_alignment_assembler.pm line 66
```

Remembering [an issue](https://github.com/PASApipeline/PASApipeline/issues/99#issuecomment-479699339) I had last time I needed to run it, this line tests whether the pasa binary can be called with `which pasa`, which of course only works when pasa is in the $PATH.

So, to double check:
```
docker run --rm pasapipeline/pasapipeline:latest which pasa
```
Nope, not in the $PATH in the container. I was able to symlink it to fix this at run-time in the container though.

I suggest symlinking the pasa executable into a directory in the $PATH or adding the /usr/local/src/PASApipeline/bin directory to it inside the container.

Thanks!

**Comment by brianjohnhaas** [comment]
HI,

The Launch_PASA_pipeline.pl  puts the pasa binary into the PATH setting,
but I can see that if you run the assembly script directly instead of by
the wrapper, this could be an issue.

Leave this issue open and we'll copy the pasa binary into /usr/local/bin in
the next docker build.

best,

~b

On Thu, Aug 29, 2019 at 3:05 AM Jeffrey Grover <notifications@github.com>
wrote:
>
> Hey there,
>
> After updating some things on our lab's server I now get some annoying
perl version mismatch errors related to the sql perl modules. However, I
figured I could just run the Docker image instead.
>
> But, I got a bunch of the following error:
>
> terminated abnormally: Error, pasa binary [] isn't executable or couldn't
be found. at
/usr/local/src/PASApipeline/PerlLib/CDNA/PASA_alignment_assembler.pm line 66
>
> Remembering an issue I had last time I needed to run it, this line tests
whether the pasa binary can be called with which pasa, which of course only
works when pasa is in the $PATH.
>
> So, to double check:
>
> docker run --rm pasapipeline/pasapipeline:latest which pasa
>
> Nope, not in the $PATH in the container. I was able to symlink it to fix
this at run-time in the container though.
>
> I suggest symlinking the pasa executable into a directory in the $PATH or
adding the /usr/local/src/PASApipeline/bin directory to it inside the
container.
>
> Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by groverj3** [comment]
That makes sense!

Thanks, Brian.

**Comment by groverj3** [comment]
Ran into another missing binary, of course because I'm running the individual scripts. So yeah, all the contents of the bin directory should be linked. That solves everything.

**Comment by brianjohnhaas** [comment]
I'll have docker copy the PASAHOME/bin/* into /usr/local/bin for the upcoming release
