### ISSUE TITLE
Incorrect alignment in  alignment.validations.output

### ISSUE THREAD

**Issue by YibiChen** [PASApipeline/PASApipeline#152]
Hello there,

I was using the alignments marked as "OK"  in alignment.validations.output to search for potiential RNA edit sites. However, I found some of the aligenmnt seems incorrect. For example, here is a single line from alignment.validations.output.
```
#prog   acc     cluster_link_id align_id        scaffold        num_segs        aligned_orient  spliced_orient  alignment_valid coord_span      avg_per_ID      per_len_aligned score   alignment       validation_comment
blat    CCS_m54261_181109_043728/22741810/ccs   907171  453205  scf7180000030061        2       +       -       OK      236249-239623   99.9392071688943        100     328999.87       orient(a+/s-) align: 236249(1)-236681(433)>CT....AC<236764(434)-239623(3292)
```
So I aligned CCS_m54261_181109_043728/22741810/ccs:1-433 with scf7180000030061:236249-23668 and got unaligned head (30bp) and tail like this:
```
236249-236681      1 ---------------------------------GATAGCAGTTGTGGTGG     17
                                                      |||||||||||||||||
1-433              1 TGGATTGATATGTAATACGACTCACTATAGGGTGATAGCAGTTGTGGTGG     50

.....................skip well-aligned region.............................

236249-236681    368 CTTAACCCTGAGCCCGTGGGCCCCCAAAAAGCCCTAACCCCTAACCCTAA    417
                     |||||||||||||||||||||||||||||||||
1-433            401 CTTAACCCTGAGCCCGTGGGCCCCCAAAAAGCC-----------------    433

236249-236681    418 ACCCTCAGCTCCTAAC    433
1-433            433 ----------------    433

```
Similar alignment also happen in the next block.

Then I aligned the transcript with the scaffold dirrectly using blat and got output:
```
match   mis-    rep.    N's     Q gap   Q gap   T gap   T gap   strand  Q               Q       Q       Q       T               T       T       T       block   blockSizes      qStarts  tStarts
        match   match           count   bases   count   bases           name            size    start   end     name            size    start   end     count
---------------------------------------------------------------------------------------------------------------------------------------------------------------
3295    0       0       0       1       1       3       84      +       CCS_m54261_181109_043728/22741810/ccs   3355    30      3326    scf7180000030061        404554  236245  239624  5       436,487,139,660,1573,   30,466,953,1093,1753,   236245,236763,237251,237390,238051,

```
The blat output suggests the aligned transcript segment starts from 30 rather than 1, which is agreed with the 30bp gap I found. It also report 5 blocks whereas alignment.validations.output only have 2.

Is there anything wrong with parsing blat result? 
I have the transcript and scaffold attached here.
[example.zip](https://github.com/PASApipeline/PASApipeline/files/4894282/example.zip)

**Comment by brianjohnhaas** [comment]
Hi,

I'm not sure why you're seeing this.  It looks like the transcript
alignment coordinates were truncated so that the alignment starts at
position 1 and the other coordinates were adjusted relative to this.  I
wasn't able to reproduce it when I ran PASA using your example:


pasapipeline/Launch_PASA_pipeline.pl -C -c pasa.alignAssembly.Template.txt
-t transcript.fa -g scf7180000030061.fa --ALIGNERS blat -R

when I look at the alignment.validations.output, I find:

blat CCS_m54261_181109_043728/22741810/ccs 1 1 scf7180000030061 2 + - OK
236246-239624 99.9392597087379 98.2414307004471 329399.8 orient(a+/s-)
align: 236246(31)-236681(466)>CT....AC<236764(467)-239624(3326)


If you look at the blat.gff3 file generated, do you see the truncated
coordinates?

Also, are you using the latest version of PASA?  (I'm not sure that
matters, though, because that part of the code wouldn't have been touched
in ages).

best,

~b



On Wed, Jul 8, 2020 at 11:29 PM Yibi Chen <notifications@github.com> wrote:
>
> Hello there,
>
> I was using the alignments marked as "OK" in alignment.validations.output
to search for potiential RNA edit sites. However, I found some of the
aligenmnt seems incorrect. For example, here is a single line from
alignment.validations.output.
>
> #prog   acc     cluster_link_id align_id        scaffold        num_segs
       aligned_orient  spliced_orient  alignment_valid coord_span
 avg_per_ID      per_len_aligned score   alignment       validation_comment
> blat    CCS_m54261_181109_043728/22741810/ccs   907171  453205
 scf7180000030061        2       +       -       OK      236249-239623
99.9392071688943        100     328999.87       orient(a+/s-) align:
236249(1)-236681(433)>CT....AC<236764(434)-239623(3292)
>
> So I aligned CCS_m54261_181109_043728/22741810/ccs:1-433 with
scf7180000030061:236249-23668 and got unaligned head (30bp) and tail like
this:
>
> 236249-236681      1 ---------------------------------GATAGCAGTTGTGGTGG
  17
>                                                       |||||||||||||||||
> 1-433              1 TGGATTGATATGTAATACGACTCACTATAGGGTGATAGCAGTTGTGGTGG
  50
>
> .....................skip well-aligned region.............................
>
> 236249-236681    368 CTTAACCCTGAGCCCGTGGGCCCCCAAAAAGCCCTAACCCCTAACCCTAA
 417
>                      |||||||||||||||||||||||||||||||||
> 1-433            401 CTTAACCCTGAGCCCGTGGGCCCCCAAAAAGCC-----------------
 433
>
> 236249-236681    418 ACCCTCAGCTCCTAAC    433
> 1-433            433 ----------------    433
>
> Similar alignment also happen in the next block.
>
> Then I aligned the transcript with the scaffold dirrectly using blat and
got output:
>
> match   mis-    rep.    N's     Q gap   Q gap   T gap   T gap   strand  Q
              Q       Q       Q       T               T       T       T
  block   blockSizes      qStarts  tStarts
>         match   match           count   bases   count   bases
name            size    start   end     name            size    start   end
    count
>
---------------------------------------------------------------------------------------------------------------------------------------------------------------
> 3295    0       0       0       1       1       3       84      +
CCS_m54261_181109_043728/22741810/ccs   3355    30      3326
 scf7180000030061        404554  236245  239624  5
436,487,139,660,1573,   30,466,953,1093,1753,
236245,236763,237251,237390,238051,
>
> The blat output suggests the aligned transcript segment starts from 30
rather than 1, which is agreed with the 30bp gap I found. It also report 5
blocks whereas alignment.validations.output only have 2.
>
> Is there anything wrong with parsing blat result?
> I have the transcript and scaffold attached here.
> example.zip
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by YibiChen** [comment]
Thanks for your advice. I just realize that it's the transcripted get truncated because I used transcripts after seqclean to do PASA thus the cordinates in the validation_output should refer to the "cleaned" transcripts, but I used these cordinates to get transcripts intervals from "uncleaned" transcripts.
