### ISSUE TITLE
Per-user configuration file

### ISSUE THREAD

**Issue by dy7t** [PASApipeline/PASApipeline#3]
When PASA software is centrally installed, it would be useful if each person could have their own, private config file containing MySQL credentials.

Here is one way that might work.  If PASACONF environment variable is assigned a filename, then use it as the PASA config file.  Otherwise, default to using the current value. 

Need to modify $PASAHOME/PerlLib/Pasa_conf.pm

```
$ diff Pasa_conf.pm Pasa_conf.pm-orig
15,24c15,16
< 
<   # Per-user configuration file option
< 
<     my $confFile;
<     if (-r $ENV{PASACONF}) {
<        $confFile = $ENV{PASACONF};
<     } else { 
<        $confFile = "$ENV{PASAHOME}/pasa_conf/conf.txt";
<     }
< 

---
>     
>     my $confFile = "$ENV{PASAHOME}/pasa_conf/conf.txt";
```

**Comment by brianjohnhaas** [comment]
We can certainly do that.    Over the years, I've avoided leveraging
individual user credentials, though.  Instead, whenever possible, we just
used institute-level credentials, and set it up so that as long as the
database name ended with "_pasa", the user could create databases and have
privileges needed.

I'll aim to fold this update into the next release, though.

best,

~brian


On Mon, Feb 23, 2015 at 3:47 PM, dy7t <notifications@github.com> wrote:

> When PASA software is centrally installed, it would be useful if each
> person could have their own, private config file containing MySQL
> credentials.
>
> Here is one way that might work. If PASACONF environment variable is
> assigned a filename, then use it as the PASA config file. Otherwise,
> default to using the current value.
>
> Need to modify $PASAHOME/PerlLib/Pasa_conf.pm
>
> $ diff Pasa_conf.pm Pasa_conf.pm-orig
> 15,24c15,16
> <
> <   # Per-user configuration file option
> <
> <     my $confFile;
> <     if (-r $ENV{PASACONF}) {
> <        $confFile = $ENV{PASACONF};
> <     } else {
> <        $confFile = "$ENV{PASAHOME}/pasa_conf/conf.txt";
> <     }
> <
> ---
> >
> >     my $confFile = "$ENV{PASAHOME}/pasa_conf/conf.txt";
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PASApipeline/PASApipeline/issues/3>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by eburgueno** [comment]
Hello, was this ever implemented? it is one of major blockers we have deploying PASA in our cluster.

Our users can create individual or semi-shared databases on our MariaDB server, but right now everyone is forced to have their own copy of the PASA pipeline, which quickly gets out of sync every time there's a new release.

**Comment by brianjohnhaas** [comment]
Not yet.  I'll aim to do this in the next release.

Best,

-Brian
(by iPhone)

**Comment by brianjohnhaas** [comment]
users will be able to set env var PASACONF to point to their own personal mysql settings file in the upcoming release.
