### ISSUE TITLE
DBD::mysql::db do failed: Data too long for column 'model_id' at row 1 

### ISSUE THREAD

**Issue by yplee614** [PASApipeline/PASApipeline#57]
we got error, how to fix it

## Processing CMD: 
16:32:26        CMD: /home/yplee/reannotation_v4.1/software/PASApipeline-pasa-v2.2.0/scripts/..//scripts/Load_Current_Gene_Annotations.dbi -c annotCompare.config -g F_vesca_H4_V4.1.fasta -P augustus_combine.gff  > pasa_run.log.dir/output.annot_loading.10197.out

Warning, no genes retrieved for contig_id: contig_13
Warning, no genes retrieved for contig_id: contig_18
Warning, no genes retrieved for contig_id: contig_8

## Processing CMD: 
16:59:08        CMD: /home/yplee/reannotation_v4.1/software/PASApipeline-pasa-v2.2.0/scripts/..//scripts/cDNA_annotation_comparer.dbi -G F_vesca_H4_V4.1.fasta --CPU 2 -M newgenome1  > pasa_run.log.dir/newgenome1.annotation_compare.10197.out
DBD::mysql::db do failed: Data too long for column 'model_id' at row 1 at /home/yplee/reannotation_v4.1/software/PASApipeline-pasa-v2.2.0/scripts/..//PerlLib/Mysql_connect.pm line 162.
Thread 23 terminated abnormally: failed query: <insert annotation_updates (gene_id, model_id, alt_splice_flag, before_gene_obj, after_gene_obj, compare_id, is_valid, have_before, have_after, is_novel_flag) values (?,?,?,?,?,?,?,?,?,?)>     values: gene.g562.t1 gene.g563.t1 gene.g564.t1 gene.g566.t1 gene.g568.t1 gene.g534.t1 gene.g536.t1 gene.g540.t1 gene.g542.t1 gene.g545.t1 gene.g548.t1 gene.g552.t1 gene.g579.t1 gene.g581.t1 gene.g586.t1 gene.g587.t1 model.g562.t1 model.g563.t1 model.g564.t1 model.g566.t1 model.g568.t1 model.g534.t1 model.g536.t1 model.g540.t1 model.g542.t1 model.g545.t1 model.g548.t1 model.g552.t1 model.g579.t1 model.g581.t1 model.g586.t1 model.g587.t1

**Comment by nathanweeks** [comment]
Hi @yplee614 ,
If you have an existing PASA database for which you want to modify (e.g., double) the lengths of model_id columns:

```
ALTER TABLE annotation_link MODIFY model_id VARCHAR(400);
ALTER TABLE annotation_store MODIFY model_id VARCHAR(400);
ALTER TABLE annotation_updates MODIFY model_id VARCHAR(400);
```
Otherwise, if you're starting over with an empty database, you could modify the definitions of these columns in the schema/cdna_alignment_mysqlschema before running PASA.

I'll point out that the forthcoming (once I can set aside enough free time to get this finished & merged) SQLite-enabled version of PASA (https://github.com/PASApipeline/PASApipeline/pull/43) will obviate the need for adjustment of character column lengths, as any column with [text affinity](https://www.sqlite.org/datatype3.html) in SQLite can store strings of (by default) length [1 billion](https://www.sqlite.org/limits.html#max_length).
